### ISSUE TITLE
Lock Triggers

### ISSUE THREAD

**Issue by shinji62** [github-api/github-api#536]
Hi,

I have some issue with Jenkins most of my Job which are scheduled(cron) are never running on time or even randomly.

One of my guess based on the logs below is that the Github api is using the Trigger too much.

Not sure what is causing my job to not be trigger on time. The only thing I found was this thread.

```
jenkins.util.Timer [#4]
"jenkins.util.Timer [#4]" Id=127 Group=main RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	-  locked java.io.BufferedInputStream@154ae878
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
	-  locked sun.net.www.protocol.http.HttpURLConnection@687449ff
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	-  locked sun.net.www.protocol.http.HttpURLConnection@687449ff
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.kohsuke.github.Requester.parse(Requester.java:615)
	at org.kohsuke.github.Requester.parse(Requester.java:607)
	at org.kohsuke.github.Requester.access$200(Requester.java:74)
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:518)
	at org.kohsuke.github.Requester$PagingIterator.hasNext(Requester.java:494)
	at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:44)
	at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:32)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.getPRCommitAuthor(GhprbPullRequest.java:445)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:222)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:179)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:159)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:371)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:278)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:226)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	Number of locked synchronizers = 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@79f77b4f
```

**Comment by shinji62** [comment]
@bitwiseman any idea ?

**Comment by bitwiseman** [comment]
@shinji62  
From the log you provided I can't tell what is occurring. 
I would think `GhprbTrigger` would be my first check.  I'm wondering why it is this stack. 

@kohsuke  
Do you have thoughts? 

 
o you have test instance you can try some things on?

**Comment by shinji62** [comment]
@bitwiseman Tell me what you need, dump logs etc .. I will put it there.

One others thing I saw it's our repository have around 4000 issues so seems the plugin ghprb use `` https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java#L145 to get only OpenPull request but in the logs I can see that Jenkins is looking for Closed one too.

**Comment by bitwiseman** [comment]
@shinji62 
Can you run a cron without Ghprb?
[This SO article](https://stackoverflow.com/questions/24885418/what-does-number-of-locked-synchronizers-1-in-a-stacktrace-mean) seems to indicated that the locked message is not related to the problem.  Is there more output?

**Comment by shinji62** [comment]
I try and work just run randomly.

**Comment by bitwiseman** [comment]
Closing for now.  Please comment with more info if you see this again.
