### ISSUE TITLE
Create or Update file fails  when content length > 57 

### ISSUE THREAD

**Issue by asthinasthi** [github-api/github-api#638]
**Describe the bug**
When we invoke [commit()](https://github.com/github-api/github-api/blob/d1507f26668950508e0bf242c34cdb599003991a/src/main/java/org/kohsuke/github/GHContentBuilder.java#L105) with [content](https://github.com/github-api/github-api/blob/d1507f26668950508e0bf242c34cdb599003991a/src/main/java/org/kohsuke/github/GHContentBuilder.java#L82) length > 57 

The API fails with 422, invalid Base 64 encoding

If we have a content `1234567890123456789012345678901234567890123456789012345678` of length 58. 
### Base64 encoding is
```
MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3OA==
```

### MIME encoding looks like
```
MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3
OA==
```
MIME encoding breaks the string into chunks of 76. This is rejected by Github API

This could be due to the recent change ?
https://github.com/github-api/github-api/blob/d1507f26668950508e0bf242c34cdb599003991a/src/main/java/org/kohsuke/github/GHContentBuilder.java#L71
**To Reproduce**
Invoke the [method](https://github.com/github-api/github-api/blob/d1507f26668950508e0bf242c34cdb599003991a/src/main/java/org/kohsuke/github/GHContentBuilder.java#L105) with content of length >57 

**Expected behavior**
The commit must be successful

**Desktop (please complete the following information):**
1.102-SNAPSHOT

**Additional context**
I was able to fix this issue locally by using `Base64.getEncoder().encodeToString()`

**Comment by bitwiseman** [comment]
@asthinasthi 
The change you linked (#631) hasn't been publish in a release yet - if you're you using `v1.101` it doesn't have this change. 

I'm pretty sure I specifically used the MIME encoding because the non-MIME produced an error. Also, if you look at what comes back from GitHub it is MIME encoded.  This SO answer agrees with this: https://stackoverflow.com/a/54302528/1637252 .
Could you take a minute to try this with a clean build from `master` (without your change)?

**Comment by asthinasthi** [comment]
Sorry, my bad again. I jumped the gun and used 1.102-SNAPSHOT to build a patch for my internal use.

But I see the issue still exists with MIME type encoding when I use the `1.102-SNAPSHOT`

I am testing like this:

```
  @Test
  public void testMIMESmall() throws IOException {

    String login = "asthinasthi";
    String oauthAccessToken = "";

    GitHub gitHub = GitHub.connect(login, oauthAccessToken);

    GHRepository ghRepository = gitHub.getRepository("asthinasthi/test-github-api");
    GHContentBuilder ghContentBuilder =  ghRepository.createContent();
    ghContentBuilder.message("Some commit msg");
    ghContentBuilder.path("MIME-Small.md");
    ghContentBuilder.content("123456789012345678901234567890123456789012345678901234567");
    ghContentBuilder.commit();
  }

  @Test
  public void testMIMELong() throws IOException {

    String login = "asthinasthi";
    String oauthAccessToken = "";

    GitHub gitHub = GitHub.connect(login, oauthAccessToken);

    GHRepository ghRepository = gitHub.getRepository("asthinasthi/test-github-api");
    GHContentBuilder ghContentBuilder =  ghRepository.createContent();
    ghContentBuilder.message("Some commit msg");
    ghContentBuilder.path("MIME-Long.md");
    ghContentBuilder.content("1234567890123456789012345678901234567890123456789012345678");
    ghContentBuilder.commit();
  }
```
`testMIMESmall()` works fine 
but 
`testMIMELong` gives a 422

## Stack Trace

```
org.kohsuke.github.HttpException: {"message":"content is not valid Base64","documentation_url":"https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}

	at org.kohsuke.github.Requester.handleApiError(Requester.java:903)
	at org.kohsuke.github.Requester._to(Requester.java:415)
	at org.kohsuke.github.Requester.to(Requester.java:353)
	at org.kohsuke.github.GHContentBuilder.commit(GHContentBuilder.java:106)
	at org.kohsuke.github.TestMIME.testMIMELong(TestMIME.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.kohsuke.github.HttpException: Server returned HTTP response code: 422, message: 'Unprocessable Entity' for URL: https://api.github.com/repos/asthinasthi/test-github-api/contents/MIME-Long.md
	at org.kohsuke.github.Requester.parse(Requester.java:840)
	at org.kohsuke.github.Requester.parse(Requester.java:782)
	at org.kohsuke.github.Requester._to(Requester.java:393)
	... 25 more
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/asthinasthi/test-github-api/contents/MIME-Long.md
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.kohsuke.github.Requester.parse(Requester.java:818)
	... 27 more
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/asthinasthi/test-github-api/contents/MIME-Long.md
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.kohsuke.github.Requester.parse(Requester.java:790)
	... 27 more
```

**Comment by bitwiseman** [comment]
Great, thanks for the clear testcase.  Would you like to submit a PR with the fix?  If not, I'll get to it sometime this week.

**Comment by asthinasthi** [comment]
Yes, I can send in a PR.  But I saw some more places where we are doing MIME encoding.
https://github.com/github-api/github-api/search?q=Base64.&unscoped_q=Base64.

Do we roll it back everywhere else?

**Comment by bitwiseman** [comment]
Funny thing, when submitting changes you have to not do MIME encoded Base64, but when returning results GitHub sends MIME encoded Base64.

**Comment by bitwiseman** [comment]
@asthinasthi 
I've submitted #650.  Could you give it a try and make sure it works for you?

**Comment by asthinasthi** [comment]
Works fine. Thanks!
